"""
Data Models and Types for Infix-to-Prefix Conversion.

Defines structured representations for tokens, algorithm execution steps,
and complete conversion results.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Dict, Any


class TokenType(str, Enum):
    OPERAND = "OPERAND"
    OPERATOR = "OPERATOR"
    LEFT_PAREN = "LEFT_PAREN"
    RIGHT_PAREN = "RIGHT_PAREN"


# Standard operator properties
OPERATOR_PRECEDENCE: Dict[str, int] = {
    "^": 3,
    "*": 2,
    "/": 2,
    "%": 2,
    "+": 1,
    "-": 1,
    "(": 0,
    ")": 0,
}

OPERATOR_ASSOCIATIVITY: Dict[str, str] = {
    "^": "Right",
    "*": "Left",
    "/": "Left",
    "%": "Left",
    "+": "Left",
    "-": "Left",
}


@dataclass
class Token:
    """Represents a lexical token in an expression."""
    value: str
    token_type: TokenType
    precedence: int = 0
    associativity: str = "None"

    @classmethod
    def from_string(cls, val: str) -> "Token":
        if val in ("(", ")"):
            ttype = TokenType.LEFT_PAREN if val == "(" else TokenType.RIGHT_PAREN
            return cls(value=val, token_type=ttype, precedence=0, associativity="None")
        if val in OPERATOR_PRECEDENCE:
            return cls(
                value=val,
                token_type=TokenType.OPERATOR,
                precedence=OPERATOR_PRECEDENCE[val],
                associativity=OPERATOR_ASSOCIATIVITY.get(val, "Left")
            )
        return cls(value=val, token_type=TokenType.OPERAND, precedence=0, associativity="None")


@dataclass
class AlgorithmStep:
    """
    Immutable snapshot of one distinct algorithm event during conversion.
    Allows exact time-travel replay and pedagogical explanation.
    """
    step_number: int
    stage: str                  # e.g., "POSTFIX_CONVERSION", "REVERSE_INPUT", etc.
    token: str                  # Current token being inspected
    action: str                 # Short description of the operation (e.g. "PUSH '+'", "POP '*'")
    stack_state: List[str]      # Copy of stack elements [bottom, ..., top]
    output_state: List[str]     # Copy of current output tokens
    reason: str                 # Pedagogical explanation of WHY this occurred
    operation_type: str         # "PUSH", "POP", "PEEK", "OUTPUT", "MATCH", "FINAL_POP", "INFO"
    top_element: Optional[str] = None
    incoming_token: Optional[str] = None

    @property
    def stack_display(self) -> str:
        """String representation of the stack for table displays."""
        if not self.stack_state:
            return "[ ]"
        return "[" + ", ".join(self.stack_state) + "]"

    @property
    def output_display(self) -> str:
        """String representation of the output for table displays."""
        if not self.output_state:
            return ""
        return " ".join(self.output_state)


@dataclass
class ConversionResult:
    """
    Complete report generated by the Infix-to-Prefix conversion process.
    """
    original_infix: str
    tokens: List[str]
    reversed_tokens: List[str]
    swapped_tokens: List[str]
    postfix_tokens: List[str]
    prefix_tokens: List[str]
    postfix_expression: str
    prefix_expression: str
    all_steps: List[AlgorithmStep]
    postfix_steps: List[AlgorithmStep]  # Primary stack operation steps
    stack_activity: Dict[str, Dict[str, int]]  # Operator -> {'push': X, 'pop': Y, 'peek': Z}
    is_valid: bool = True
    error_message: Optional[str] = None
    error_position: Optional[int] = None
